### ISSUE TITLE
添加录屏软件

### ISSUE THREAD

**Issue by WHMyyds** [kriastans/Awesome-Iwb#14]
我不知道大佬愿不愿意添加，而且我对markdown语言不大熟练，我先发个issue问问
我推荐[pearrec](https://github.com/027xiguapi/pear-rec)

**Comment by MKStoler4096** [comment]
@WHMyyds 这个是一体机和电子白板实用软件合集
貌似本应用偏离主题……

**Comment by WHMyyds** [comment]
有时候需要录课需要啊，我是电教，这种事我经历过

在 2024-09-24 21:03:43，MKStoler ***@***.***> 写道：


@WHMyyds 这个是一体机和电子白板实用软件合集
貌似本应用偏离主题……

**Comment by WHMyyds** [comment]
你收网址嘛
[relaxing clock](https://relaxingclock.com)电子时钟也在github开原，我用着不错

**Comment by WHMyyds** [comment]
？

**Comment by WHMyyds** [comment]
OK
